# Generated by Django 6.0.1 on 2026-01-30 03:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('polls', '0004_remove_vote_unique_vote_per_user_choice_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='votes',
        ),
    ]
